name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - main
    - develop

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
      with:
        extra_args: -a --hook-stage manual

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.9]
        runs-on: [ubuntu-latest, macos-latest] # windows-latest]

        include:
        - python-version: pypy-3.6
          runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install automake on macOS
      if: runner.os == 'macOS'
      run: brew install automake

    - name: Install Fortran on macOS
      if: runner.os == 'macOS'
      run: brew install gfortran-8

    - name: Install SWIG on macOS
      if: runner.os == 'macOS'
      run: brew install swig

    - name: Install package
      run: python -m pip install -e .[test] -v

    - name: Test package
      run: python -m pytest -s -ra
